chemparameter<-ncol(data.frame(chem_basin$chemparameter))
Magnesium <-lapply(chemparameter, function(x) NULL)
Nitrite<-lapply(chemparameter, function(x) NULL)
Nitrate<-lapply(chemparameter, function(x) NULL)
Ammonia<-lapply(chemparameter, function(x) NULL)
Calcium<-lapply(chemparameter, function(x) NULL)
Hardness<-lapply(chemparameter, function(x) NULL)
Organic.Nitrogen<-lapply(chemparameter, function(x) NULL)
Ortho.Phosphate<-lapply(chemparameter, function(x) NULL)
pH<-lapply(chemparameter, function(x) NULL)
Total.Kjeldahl.Nitrogen<-lapply(chemparameter, function(x) NULL)
Total.Nitrogen<-lapply(chemparameter, function(x) NULL)
Total.Solids<-lapply(chemparameter, function(x) NULL)
Total.Suspended.Solids<-lapply(chemparameter, function(x) NULL)
Turbidity<-lapply(chemparameter, function(x) NULL)
Alkalinity<-lapply(chemparameter, function(x) NULL)
Total.Phosphorous<-lapply(chemparameter, function(x) NULL)
Chloride<-lapply(chemparameter, function(x) NULL)
Total.Organic.Carbon<-lapply(chemparameter, function(x) NULL)
Silica<-lapply(chemparameter, function(x) NULL)
Chlorophyll.a.Plankton<-lapply(chemparameter, function(x) NULL)
Nitrate.Nitrite<-lapply(chemparameter, function(x) NULL)

for (i in chemparameter) {
  Magnesium[[i]] <- data.frame(chem_basin[chem_basin$chemparameter=="Magnesium"&chem_basin$duplicate==0,])
  Nitrite[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Nitrite"&chem_basin$duplicate==0,])
  Nitrate[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Nitrate"&chem_basin$duplicate==0,])
  Ammonia[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Ammonia"&chem_basin$duplicate==0,])
  Calcium[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Calcium"&chem_basin$duplicate==0,])
  Hardness[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Hardness"&chem_basin$duplicate==0,])
  Organic.Nitrogen[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Organic Nitrogen"&chem_basin$duplicate==0,])
  Ortho.Phosphate[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Ortho Phosphate"&chem_basin$duplicate==0,])
  pH[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="pH"&chem_basin$duplicate==0,])
  Total.Kjeldahl.Nitrogen[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Total Kjeldahl Nitrogen"&chem_basin$duplicate==0,])
  Total.Nitrogen[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Total Nitrogen"&chem_basin$duplicate==0,])
  Total.Solids[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Total Solids"&chem_basin$duplicate==0,])
  Total.Suspended.Solids[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Total Suspended Solids"&chem_basin$duplicate==0,])
  Turbidity[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Turbidity"&chem_basin$duplicate==0,])
  Alkalinity[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Alkalinity"&chem_basin$duplicate==0,])
  Total.Phosphorous[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Total Phosphorous"&chem_basin$duplicate==0,])
  Chloride[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Chloride"&chem_basin$duplicate==0,])
  Total.Organic.Carbon[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Total Organic Carbon"&chem_basin$duplicate==0,])
  Silica[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Silica"&chem_basin$duplicate==0,])
  Chlorophyll.a.Plankton[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Chlorophyll-a Plankton"&chem_basin$duplicate==0,])
  Nitrate.Nitrite[[i]]<-data.frame(chem_basin[chem_basin$chemparameter=="Nitrate/Nitrite"&chem_basin$duplicate==0,])
}







for (i in 1:length(chemunique)) {
  Magnesium[[i]] <- data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Nitrite[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Nitrate[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Ammonia[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Calcium[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Hardness[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Organic.Nitrogen[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Ortho.Phosphate[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  pH[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Total.Kjeldahl.Nitrogen[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Total.Nitrogen[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Total.Solids[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Total.Suspended.Solids[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Turbidity[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Alkalinity[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Total.Phosphorous[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Chloride[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Total.Organic.Carbon[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Silica[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Chlorophyll.a.Plankton[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  Nitrate.Nitrite[[i]]<-data.frame(chem_basin[chem_basin$chemparameter==chemunique[i]&chem_basin$duplicate==0,])
  numsample<- vector(mode = "numeric",length=length(chemunique))
  